const SET_AUTH = "SET_AUTH";
const SET_USER = "SET_USER";
const SET_LOADING = "SET_LOADING";
const SET_INITIALIZED = "SET_INITIALIZED";
const ADD_FILTER = "ADD_FILTER";
const REMOVE_FILTER = "REMOVE_FILTER";

export {
  SET_AUTH,
  SET_USER,
  SET_LOADING,
  SET_INITIALIZED,
  ADD_FILTER,
  REMOVE_FILTER
};
